### ISSUE TITLE
Idea: machine-readable identification file

### ISSUE THREAD

**Issue by brandmaier** [cjvanlissa/worcs#14]
Would it make sense to define that every worcs project needs to have a standardized, machine-readable file that can be used to determine whether a given directory is a worcs-compatible directory. I suggest that the minimal requirement could be the existence of a file called ".worcs". 
It would make sense if this file also stored the version of the worcs specification. The specification may change over time and it would be important for automatic parsers to easily identify which version of the specification a given project adheres to. The .worcs file could have a YAML structure, which defines the version of specification that was used. For example, it could have a single line:
`version: 1.0`
In the future, this will be very useful for automatically creating indices of worcs directories once there are different specifications around.

**Comment by cjvanlissa** [comment]
Smart! If we do this - would it be congruent with this idea to store project-relevant information in that same file? Like the checksums for data? These are currently in a `.csv`, which I'm not super happy about.

**Comment by brandmaier** [comment]
I think so. We could allow for all sorts of meta information. It could look like this:

```
specification: worcs-1.0
maintainer: CVL (email@cvl.com)
checksums:
   data.csv: F628AB6283
   manuscript.Rmd: FEFA451D98
doi: http://dx.doi.org/10.1037/a0028240

```
